global:
  replicaCount: 1
  image:
    pullPolicy: "Always"
  serviceAccountName: "terminal-sa"

backend:
  image:
    name: 
    tag:
  service:
    port: 8080
    type: "NodePort"
  ingress:
    host: "api.localhost"
  initMessage: "TEST MESSAGE FROM K8S"

frontend:
  image:
    name:
    tag:
  service:
    port: 8080
    type: "NodePort"
  ingress:
    host: "terminal.localhost"