global:
  replicaCount: 1
  image:
    pullPolicy: "Always"
  serviceAccountName: "terminal-sa"

backend:
  image:
    name: "jakubdebosz/backend"
    tag: "latest"
  service:
    port: 8080
    type: "NodePort"
  ingress:
    host: "api.localhost"
  initMessage: "Init message display from separate values file"

frontend:
  image:
    name: "jakubdebosz/frontend"
    tag: "latest"
  service:
    port: 8080
    type: "NodePort"
  ingress:
    host: "terminal.localhost"